{{- if and .Values.monitoring.enabled .Values.flyte.cacheservice.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-cacheservice
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      platform.union.ai/prometheus-group: "union-services"
      app.kubernetes.io/name: {{ template "cacheservice.name" . }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: http-metrics
      interval: 1m
      path: /metrics
      honorLabels: true
{{- end }}
