apiVersion: v1
kind: Service
metadata:
  name: syncresources
  labels:
    platform.union.ai/prometheus-group: "union-services"
    {{- include "clusterresourcesync.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 10254
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    {{- include "clusterresourcesync.selectorLabels" . | nindent 6 }}
