{{- $autoscaling := include "console.autoscaling" . | fromYaml }}
{{- $replicaCount := .Values.console.replicaCount | int }}
{{- if or (ge $replicaCount 1) (and $autoscaling.enabled (ge $autoscaling.maxReplicas 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  minAvailable: "33%"
  selector:
    matchLabels:
      {{- include "console.selectorLabels" . | nindent 6 }}
{{- end }}
