apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    platform.union.ai/prometheus-group: "union-services"
    {{- include "console.labels" . | nindent 4 }}
  {{- with .Values.console.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.console.service.type }}
  ports:
  - port: {{ .Values.console.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if .Values.console.service.appProtocol }}
    appProtocol: {{ .Values.console.service.appProtocol }}
    {{- end }}
  - port: {{ .Values.console.service.metricsPort }}
    targetPort: http-metrics
    protocol: TCP
    name: http-metrics
  selector:
    {{- include "console.selectorLabels" . | nindent 4 }}
