{{- if include "singleNamespace" . }}
apiVersion: v1
kind: PodTemplate
metadata:
  name: task-template
  namespace: {{ .Release.Namespace }}
template:
  spec:
    serviceAccountName: union
    containers:
      - name: default
        image: docker.io/rwgrim/docker-noop
{{- end }}
