{{- if and (not .Values.clusterresourcesync.enabled) .Values.low_privilege }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: union
  namespace: {{ .Release.Namespace }}
  annotations:
    {{.Values.userRoleAnnotationKey}}: {{.Values.userRoleAnnotationValue}}
automountServiceAccountToken: true
{{- end }}