{{- if (index .Values "controlplane" | default dict).enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: union
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unionai.labels" (dict "key" "union" "Release" .Release "Values" .Values "Chart" .Chart) | nindent 4 }}
{{- end }}
