{{- if .Values.proxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "proxy.serviceAccountName" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
  {{- with include "global.serviceAccountAnnotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.low_privilege }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "proxy.serviceAccountName" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - events
      - flyteworkflows
      - pods/log
      - pods
      - rayjobs
      - resourcequotas
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.low_privilege }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "proxy.serviceAccountName" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.low_privilege }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "proxy.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
