apiVersion: v2
name: dataplane-crds
description: Deploys the Union dataplane CRDs.
type: application
icon: "https://i.ibb.co/JxfDQsL/Union-Symbol-yellow-2.png"
version: 2026.1.1
appVersion: 2026.1.1
kubeVersion: ">= 1.28.0-0"
