{{- if and (.Values.secrets.admin.enabled) }}
{{- $secret := .Values.secrets.admin.clientSecret | required ".Values.secrets.admin.clientSecret is required when admin client credentials has been enabled." -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: union-secret-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # TODO(rob): update or configure operator to use client_secret like all the other components.
  app_secret: {{ $secret | b64enc | toString }}
  client_secret: {{ $secret | b64enc | toString }}
{{- end }}