# This values file customizes the helm chart to install Union Dataplane into a single namespace and ensure
# no cluster-wide permissions are needed.
low_privilege: true
fluentbit:
  enabled: false
config:
  operator:
    billableUsageCollector:
      enabled: false
    collectUsages:
      enabled: false
    serverlessCollectUsages:
      enabled: false
    dependenciesHeartbeat:
      # -- Define the propeller health check endpoint.
      propeller:
        endpoint: '{{ include "propeller.health.url" . }}'
      # -- Define the operator proxy health check endpoint.
      proxy:
        endpoint: '{{ include "proxy.health.url" . }}'
      # -- This removes the prometheus health endpoint
      prometheus: null
    limitNamespace: "{{ .Release.Namespace }}"
    disableClusterPermissions: true
  core:
    propeller:
      limit-namespace: "{{ .Release.Namespace }}"
    webhook:
      disableCreateMutatingWebhookConfig: true
  namespace_config:
    namespace_mapping:
      template: "{{ .Release.Namespace }}"
prometheus:
  enabled: false
executor:
  propeller:
    limit-namespace: "{{ .Release.Namespace }}"
  raw_config:
    namespace_mapping:
      template: "{{ .Release.Namespace }}"
clusterresourcesync:
  enabled: false
opencost:
  enabled: false
namespaces:
  enabled: false