fluentbit:
  enabled: false
config:
  operator:
    billableUsageCollector:
      enabled: false
    collectUsages:
      enabled: false
    serverlessCollectUsages:
      enabled: false
    dependenciesHeartbeat:
      # -- Define the propeller health check endpoint.
      propeller:
        endpoint: '{{ include "propeller.health.url" . }}'
      # -- Define the operator proxy health check endpoint.
      proxy:
        endpoint: '{{ include "proxy.health.url" . }}'
      prometheus: null
  core:
    propeller:
      limit-namespace: "{{ .Release.Namespace }}"
    webhook:
      disableCreateMutatingWebhookConfig: true
  namespace_config:
    namespace_mapping:
      template: "{{ .Release.Namespace }}"
low_privilege: true
prometheus:
  prometheus:
    enabled: false
executor:
  propeller:
    limit-namespace: "{{ .Release.Namespace }}"
  raw_config:
    namespace_mapping:
      template: "{{ .Release.Namespace }}"
clusterresourcesync:
  enabled: false
opencost:
  enabled: false
