# This values file installs Union Dataplane into a single namespace and ensures no cluster-wide
# permissions are needed.
#
# Single-namespace config (limitNamespace, limit-namespace, namespace_mapping, clusterresourcesync)
# is auto-injected by templates when namespaces.enabled is false.
low_privilege: true
namespaces:
  enabled: false
fluentbit:
  enabled: false
config:
  operator:
    billableUsageCollector:
      enabled: false
    collectUsages:
      enabled: false
    serverlessCollectUsages:
      enabled: false
    dependenciesHeartbeat:
      # -- Define the propeller health check endpoint.
      propeller:
        endpoint: '{{ include "propeller.health.url" . }}'
      # -- Define the operator proxy health check endpoint.
      proxy:
        endpoint: '{{ include "proxy.health.url" . }}'
      # -- This removes the prometheus health endpoint
      prometheus: null
    disableClusterPermissions: true
  core:
    webhook:
      disableCreateMutatingWebhookConfig: true
prometheus:
  enabled: false
opencost:
  enabled: false
cost:
  enabled: false
monitoring:
  enabled: false
metrics-server:
  enabled: false
flytepropeller:
  priorityClassName: ''
