{{- if and (not .Values.flytepropeller.enabled) .Values.flytepropellerwebhook.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-propeller-webhook-config
  namespace: {{ .Release.Namespace }}
data:
  core.yaml: |
{{ include "propeller.webhookConfigMinimal" . | nindent 4 }}
{{- end }}
