{{- if .Values.flytepropellerwebhook.enabled }}
{{- if .Values.flytepropellerwebhook.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flytepropeller-webhook
  labels:
    app: flytepropeller-webhook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flytepropeller-webhook
  minReplicas: {{ .Values.flytepropellerwebhook.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.flytepropellerwebhook.autoscaling.maxReplicas }}
  metrics:
    {{ .Values.flytepropellerwebhook.autoscaling.metrics | toYaml | nindent 4 }}
{{- end }}
{{- end }}
