{{- if and (.Values.flytepropellerwebhook.autoscaling.enabled) .Values.flytepropellerwebhook.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: union-webhook
  labels:
    app: union-webhook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: union-pod-webhook
  minReplicas: {{ .Values.flytepropellerwebhook.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.flytepropellerwebhook.autoscaling.maxReplicas }}
  metrics:
    {{ .Values.flytepropellerwebhook.autoscaling.metrics | toYaml | nindent 4 }}
{{- end }}
