{{- if .Values.flyteconnector.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "flyteconnector.name" . }}
  labels:
    {{- include "flyteconnector.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "flyteconnector.name" . }}
  minReplicas: {{ .Values.flyteconnector.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.flyteconnector.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.flyteconnector.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.flyteconnector.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.flyteconnector.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.flyteconnector.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
