{{- if .Values.flyteconnector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "flyteconnector.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "flyteconnector.labels" . | nindent 4 }}
  {{- with .Values.flyteconnector.serviceAccount.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.flyteconnector.service.clusterIP}}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: {{ .Values.flyteconnector.ports.name }}
      port: {{ .Values.flyteconnector.ports.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.flyteconnector.ports.name }}
    - name: {{ .Values.flyteconnector.prometheusPort.name }}
      port: {{ .Values.flyteconnector.prometheusPort.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.flyteconnector.prometheusPort.name }}
  selector: {{ include "flyteconnector.selectorLabels" . | nindent 4 }}
{{- end }}