{{- if .Values.flyteconnector.enabled }}
---
{{- if .Values.flyteconnector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flyteconnector.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "flyteconnector.labels" . | nindent 4 }}
  {{- with .Values.flyteconnector.serviceAccount.annotations }}
  annotations: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end}}
  {{- with .Values.flyteconnector.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{ tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}