{{- if .Values.executor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "executor.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "executor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/nodeexecutor/configmap.yaml") . | sha256sum | trunc 63 | quote }}
      labels:
        {{- include "executor.podLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1337
      serviceAccountName: flytepropeller-system # TODO: update `executor` ServiceAccount to have required permissions
      volumes:
        - name: config-volume
          configMap:
            name: executor
        {{- if .Values.secrets.admin.enable }}
        - name: secret-volume
          secret:
            secretName: {{ .Values.operator.secretName }}
        - name: auth
          secret:
            secretName: {{ .Values.operator.secretName }}
        {{- end }}
      {{- with .Values.executor.additionalVolumes -}}
      {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: executor
          image: "{{ .Values.image.union.repository }}:{{ .Values.image.union.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.union.pullPolicy }}
          command:
            - executor
            - serve
            - --config
            - /etc/config/*.yaml
          ports:
            - name: http
              containerPort: 8089
              protocol: TCP
            - name: metrics
              containerPort: 10254
              protocol: TCP
          env:
            {{- include "global.podEnvVars" . | nindent 12 }}
            {{- with .Values.executor.podEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: "1"
                  resource: limits.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  divisor: "1"
                  resource: limits.cpu
          resources:
            limits:
              cpu:    {{ .Values.executor.resources.limits.cpu | quote }}
              memory: {{ .Values.executor.resources.limits.memory | quote }}
            requests:
              cpu:    {{ .Values.executor.resources.requests.cpu | quote }}
              memory: {{ .Values.executor.resources.requests.memory | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            {{- if .Values.secrets.admin.enable }}
            - name: secret-volume
              mountPath: /etc/union/secret
            - name: auth
              mountPath: /etc/secrets/
            {{- end }}
          {{- with .Values.executor.additionalVolumeMounts -}}
          {{ tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
{{- end }}