{{- if .Values.executor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unionai-dataplane.fullname" . }}-executor
  labels:
    {{- include "executor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 15605
      targetPort: 15605
      protocol: TCP
      name: fasttask
  selector:
    {{- include "executor.selectorLabels" . | nindent 4 }}
{{ end }}