apiVersion: v2
name: sandbox
description: Deploys extras for sandbox testing.
type: application
icon: https://i.ibb.co/JxfDQsL/Union-Symbol-yellow-2.png
version: 2025.6.16
appVersion: 2025.2.0
kubeVersion: '>= 1.28.0'
