{{- /*
Service Monitor used specifically for Union features.
*/ -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flytepropeller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    platform.union.ai/prometheus-group: union-features
    {{- include "flytepropeller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "flytepropeller.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: debug
      path: /metrics
      honorLabels: true
      metricRelabelings:
        - sourceLabels: [__name__]
          separator: ";"
          regex: "flyte:propeller:all:round:execution_info|flyte:propeller:all:node:fast_task:fast_task_execution_duration"
          action: keep